version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vnpt_hackathon
    restart: always
    ports:
      - "6333:6333" # HTTP API Port (Dùng cho REST và Dashboard)
      - "6334:6334" # gRPC Port (Dùng cho Client hiệu năng cao)
    volumes:
      # Cấu trúc: [Đường dẫn trên máy thật]:[Đường dẫn trong container]
      - ./vectorDB/qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334